name: Tests

on:
  push:
    branches:
      - 'master/**'
      - 'feature/**'
      - 'documentation/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'w/**'
      - 'q/**'
      - 'hotfix/**'
      - 'task/**'
      - 'release/**'
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt-get update -q
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Yarn
        run: npm install -g yarn
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: run lint
        run: yarn run eslint
      - name: run build
        run: yarn build
